#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install nginx -y
ufw allow 22
ufw allow 'Nginx HTTP'
ufw enable
echo "Hello World!" > /var/www/html/index.html
service nginx start
