#!/usr/bin/env bash
#Configure a new Nginx /redirect_me redirecting to another page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 22
ufw enable
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent; }' /etc/nginx/sites-available/default
service nginx restart
