#!/usr/bin/env bash
# Script that configures a new Ubuntu machine
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 22
ufw enable
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
service nginx restart
