#!/usr/bin/env bash
# Install and configure HAproxy 
sudo apt update
sudo apt install haproxy -y
server_config=\
"
frontend  ehoneah-frontend
        bind *:80
        mode http
        default_backend ehoneah-backend
backend ehoneah-backend
        balance roundrobin
        server 513437-web-01 34.224.95.164:80 check
        server 513437-web-02 54.83.130.121:80 check
"
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
