#!/usr/bin/env bash
# displays Best School 10 times and hi in the 9.

i=0
while [ $i -lt 11 ]
do
    if [ $i = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i+=1))
done