#!/usr/bin/env bash
#bash script to print Best School 10 times
i=1
while ((i <= 10))
do
    echo "Best School"
        if [ $i -eq 9 ];
        then
            echo "hi"
        fi
    ((i+=1))
done
