#!/usr/bin/env bash
# displays Best School 10 times and hi in the 9.

i=1
while (( i <= 10 ))
do
    if [ $i = 4 ]
    then
        echo "bad luck"
    elif [ $i = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i+=1))
done