#!/usr/bin/env bash
#############################################
# displays information about the school file.
############################################
fil="school"

if [[ -e $fil ]]; then
    echo "$fil file exists"
    if [[ ! -s $fil ]]; then
	echo "$fil file is empty"
    elif [[ -s $fil ]]; then
	echo "$fil file is not empty"
    fi
    if [[ -f $fil ]]; then
	echo "$fil is a regular file"
    fi
else
    echo "$fil file does not exist"
fi
