#!/usr/bin/env bash
#############################################
# displays information about the school file.
############################################
fil="school"

if [[ -e $fil ]]; then
    echo "school file exists"
    if [[ ! -s $fil ]]; then
	echo "school file is empty"
    elif [[ -s $fil ]]; then
	echo "school file is not empty"
    fi
    if [[ -f $fil ]]; then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
